default:
  content:
    - name: "Stock Pricing Dashboard with Dash"
      path: "."
      description: "A Dash application makes it easy to transform your analysis into an interactive dashboard using Python so users can ask and answer questions in real-time, without having to touch any code.h"
      tag:
        - "Examples|Python|Dash"
      url: "/python-examples/dash/"
      image: "dash-stock-pricing.png"
