default:
  content:
    - name: "Reticulated Image Classification with Shiny and PyTorch"
      path: "."
      description: "A Shiny for R app powered by a PyTorch Model"
      tag:
        - "Examples|Python|Reticulate"
      url: "/python-examples/shiny-pytorch/"
      image: "reticulated-image-classifier.png"
